name: Build and Deploy Python App to Azure Web App - AI-Chatbot-Support

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          source venv/bin/activate
          # Example: pytest
          pytest

      - name: Zip artifact for deployment
        run: |
          source venv/bin/activate
          zip -r release.zip . -x "venv/*" "*.git/*" "*.github/*" "__pycache__/*" "release.zip"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_55DCF358BF524D3081F17D6CDB82D556 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_265697F31B3847B080484426B7E2E8B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3368265CC0CF497F8030D8C74694479E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AI-Chatbot-Support'  # Ensure exact match
          slot-name: 'Production'
          package: './release.zip'

      - name: Restart Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp restart --name AI-Chatbot-Support --resource-group <Your-Resource-Group>
        env:
          AZURE_SUBSCRIPTION: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3368265CC0CF497F8030D8C74694479E }}
